### ISSUE TITLE
Angular universal - TypeError: object is not iterable

### ISSUE THREAD

**Issue by ziuniecki** [wynfred/ngx-masonry#51]
Hi,
I'm running ngx-masonry on my SSR app. I've got error:
```
ERROR TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at NgxMasonryDirective.ngAfterViewInit
```
Error is showing because there is no images inside ngx-masonry component. I looked at source code of NgxMasonryDirective - ngAfterViewInit method and there is something like
```ts
const images = this.element.nativeElement.getElementsByTagName('img');
this.images = new Set(images);
```
It works good in browser, but at my universal app (node) there is error because of that part of code. I think node interprets differently `getElementsByTagName` method than browser...
When I set ngIf at `ngx-masonry` component like `<ngx-masonry *ngIf="elements.length > 0" [options]="myOptions">` the problem persists, but I don't know why...

Could You help me? :)

Regards,
Wojciech

**Comment by wynfred** [comment]
Hi, I released a new version that should fix the issue. Could you try 10.0.4? Thanks.

**Comment by ziuniecki** [comment]
now when there is no images it's ok, but when I put some images still have same error. I've checked what type of data getElementsByTagName returns and it's HTMLCollectionOf - Set() in nodejs can't handle it... 

I think You should try `Array.from()`

![image](https://user-images.githubusercontent.com/22814454/88485349-7b00e180-cf75-11ea-807f-a3123bac5082.png)

**Comment by se22as** [comment]
I have just upgraded to 10.0.11 and I am still seeing ngx-masonry not working in Server Side Rendering.  My list definitely contains items and I am getting the error ERROR TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
