### ISSUE TITLE
Layout issue with version 11.0.2

### ISSUE THREAD

**Issue by manuelosorio** [wynfred/ngx-masonry#80]
The change made to [src/lib/ngx-masonry.directive.ts](../blob/master/src/lib/ngx-masonry.directive.ts) in commit 66534b4711c2912f2f2bafc1fe4b58070063df37 ended up breaking the layout I had. I'm not completely sure to what that change actually does but below I'm providing links to a few screenshots to show the issue. 

**NGX-Masonry@11.0.0**
http://prnt.sc/15shks4
http://prnt.sc/15shkzv

**NGX-Masonry@11.0.2**
http://prnt.sc/15sj99m
https://prnt.sc/15sgl9r
http://prnt.sc/15sh4t2

**Comment by wynfred** [comment]
Hi, not sure how that change could cause the bug. Do you have images in that component?

**Comment by manuelosorio** [comment]
I do not have images on the component. I honestly don't know how it would affect it either.

**Comment by manuelosorio** [comment]
Component GIST: https://gist.github.com/manuelosorio/be2290111426a1aee4912dbfe890d679.
I looked furthered into the issue. It seams that this only happens when images are not the target for the masonry item. 

Pull request: #81 seams to fixed the problem when I add `[ready]='true'`
```
  <ngx-masonry [options]="masonryOptions" [ordered]="true"  class="lists-container">
      <div ngxMasonryItem [ready]='true' class="masonry-item" *ngFor="let list of masonryLists">
          ...
      </div>
  </ngx-masonry>
```

**Comment by buckon99** [comment]
I have a similar issue. My application is on Angular 12. After upgrading to NGX-Masonry@11.0.2, the masonry layout shows all images in a column, one image per row. I reverted back to NGX-Masonry@11.0.0 and it is now working again.

**Comment by wynfred** [comment]
Hi, I'm not sure if it's the same issue but I think I fixed the one in #81. Please try the new release and see if it works and feel free to reopen if it doesn't. Thank you!

**Comment by manuelosorio** [comment]
I tried the new update. I'm still having the same issue where an empty space at the top of my ngx-masonry items.

**Comment by wynfred** [comment]
Then it could be a different issue. Could you try make a stackblitz repro?

**Comment by manuelosorio** [comment]
@wynfred I made a stackblitz. I had to manually add the ngx-masonry repo as ngcc was not compiling it on stackblitz after install.

The component using ngx-masonry is `fake-list`.

https://stackblitz.com/edit/todo-demo

https://todo-demo.stackblitz.io/
